### ISSUE TITLE
Migrating content from stack exchange to docs

### ISSUE THREAD

**Issue by michaelmcandrew** [civicrm/civicrm-docs#32]
It strikes me that Stack Exchange is potentially a great source of inspiration / content for our documentation. http://civicrm.stackexchange.com/questions?sort=votes has a list of topics that we should ensure are represented in the docs.

I imagine post popular *answers* as well would be useful but I can't find the an appropriate URL for that.

We can use the content from SE as (a starting point) for the actual text, and link to the docs from a comment on the question / answer, if relevant.

Not sure what labels to attach to the issue, but thought it was worth capturing / discussing...

**Comment by seanmadsen** [comment]
+1 Yeah, I love this idea!

This is not to say that every SE question should warrant docs updates, but in some ways SE shows us where the docs are failing.

**Comment by ErichBSchulz** [comment]
I love SE!! 

But!! I think at this stage the doco is horribly split between wiki and mkdocs so I reckon major effort should be on transferring the reference material from there to the mkdocs (ie phase 1)

While this is happening the SE will function and harvest the missing piece relatively painlessly - and when the wiki transfer is complete then can use SE as a source of new content?

**Comment by seanmadsen** [comment]
+1 on prioritizing wiki

**Comment by seanmadsen** [comment]
Does anyone have ideas for processes to employ for accomplishing these tasks and bringing this issue to a state where it can be closed? I think this content migration work is important, but since it will be ongoing, we won't be able to close this issue without a separate barometer for "done".

Maybe we are done when we have a *way to track* which SE questions require docs edits? Like, it would be great if each SE question (or maybe answer?) could have a field like "(Requires docs edits -Yes/No)" and then docs editors could search SE for "Yes" to find content to capture or "NULL" to find content to decide upon. I doubt we'll be able to do this with SE. "Tags" occurred to me, but it seems like it doesn't quite fit so well. 

By gut tells me that the difficulty in creating a suitable system to track documentation needs from SE will result in this issue never moving past the "idea" stage. As such, I gently propose that we move on by closing this issue and each personally working towards creating a *culture* of documentation which encourages everyone to think "hmmm, maybe *this* should go in docs?" For example, Joe and Erich recently [made such suggestions](https://lists.civicrm.org/lists/arc/civicrm-dev/2017-02/msg00031.html) on the dev email for some content in an email. I think that as our docs improve, momentum will build, and more people will think to capture relevant info in them. 

Another idea would be to schedule a docs sprint focused on SE content migration? 

Only moving to close in an effort to keep the issue queue manageable and focused on priorities. Definitely open/curious to other ways to proceed here.

**Comment by ErichBSchulz** [comment]
so perhaps this issue needs to be reframed as "develop a system to allow tracking of high-value SE content  to dev guide"

this could be as simple as tagging questions `for dev guide` and then removing this SE tag when migrated and ensuring that there is a comment on the appropriate answers "migrated to dev guide see [link]"

how does that sound? then that policy needs documenting somewhere?

**Comment by seanmadsen** [comment]
Using SE tags still feels like we'd be hijacking the tags functionality a little bit. But all-things-considered I do like the idea. 

@ErichBSchulz I think for the tagging to be useful, we'd need more than 1 tag. I'm proposing 3 separate ones. 

In any case, I think that any changes to SE workflow should get buy-in from community members who are most involved in SE moderation. For this reason **I posted a meta question about this in SE**: 

http://meta.civicrm.stackexchange.com/questions/178/how-to-help-se-content-find-its-way-into-our-documentation

I added an "answer" with a detailed description of how I think tags would be best used here. Others please add other answers. @ErichBSchulz maybe you want to add your single-tag proposal? (I like the simplicity of it, but I prefer my 3 tag strategy because it helps with the first step of evaluating content)

**Comment by michaelmcandrew** [comment]
I am not sure that we need anything formal for this. I just wanted to get it in people's minds. It now appears to me in eric and sean's. How do we get it in other peoples? Maybe a sentence or two in https://docs.civicrm.org/dev/en/master/documentation/?

**Comment by seanmadsen** [comment]
Ok I'm going to go ahead and close this since it seems like "it is in people's minds". I like the idea of a sentence or two somewhere in the meta docs page but I feel like task of adding that sentence is small enough and insignificant enough that it's okay if I close this issue. I'm trying to get the issue queue down a bit.
