### ISSUE TITLE
How will users switch between different versions of a book?

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-docs#33]
@nganivet [raised the issue](https://github.com/civicrm/civicrm-docs/issues/15#issuecomment-275983259) of documentation users needing a clear and usable way to switch between different versions of a book. For example if a user lands on the User Guide for CiviCRM 4.6, how does this user switch to the User Guide for the most current version? What indication does the user even have that they could potentially be reading an outdated version of the docs? 

@nganivet included this screedshot in the original discussion as an example: 

![screenshot](https://cloud.githubusercontent.com/assets/3435067/22413152/9cb83444-e672-11e6-97e2-77081c3aab79.png)

**Comment by seanmadsen** [comment]
@nganivet to respond here to the point you raised, it's a bit complicated (hence the separate thread for this topic). You said "switch to another version and export to pdf as the readthedocs theme does". 

**The "readthedocs" theme actually does *not* do version switching**. 

In fact, **MkDocs doesn't even do version switching** regardless of which theme one uses with it, which is a pretty big disappointment. 

What *does* do version switching is the ReadTheDocs *hosting*, which we are not currently using. (Note: "readthedocs" can refer to: the [hosting](https://readthedocs.org/), the [theme for MkDocs](https://github.com/mkdocs/mkdocs/tree/master/mkdocs/themes/readthedocs), or the [theme for Sphinx](https://github.com/snide/sphinx_rtd_theme) &mdash; confusing!) Switching to RTD hosting would give us this version-switching feature, along with others, but I think that switch would be a *big* switch and one that personally I'm relatively opposed to. It's certainly an option, but I think it would warrant a separate thread for discussion. I'd like to keep this thread focused on how we can implement version switching within our current self-hosted docs system.

MkDocs has an [open issue](https://github.com/mkdocs/mkdocs/issues/193) with many people requesting this feature. 

There's a separate project called [mkdocs-versioned](http://d0ugal.github.io/mkdocs-versioned/) which I researched but seems to be completely useless for us because (1) is super alpha, and (2) it would not offer us any new functionality (i.e. all of its current features already exist for us within civicrm-docs).

**Comment by seanmadsen** [comment]
**Here's how I want to do version switching**

1. Provide a really nice home page at docs.civicrm.org. I've already started adding some issues in pursuit of this goal
1. Have the docs home page list all versions (and media, like PDF) for each book &mdash; we get control, and can do it right.
1. Make our custom theme link to docs.civicrm.org with very clear and intuitive link placement so that every book directs its readers back to the docs home easily

**Comment by nganivet** [comment]
Thanks for the clarification, I did not know about 'hosted'-specific features. I would personally like to:
1. keep the drop-down to switch versions in the UI, in a very similar way it was done for the wiki (including the alert if you are not on the latest). Probably in the header as there is no side-bar menu in the new theme.
2.  that the version slugs match the git branches: right now we have 'stable' instead of master, that is confusing and incorrect (4.6 is more 'stable' than the master branch since only bug fixes are rolled in). That will also alleviate potential confusion when programmers update the documentation (ie. I added a new API to master, where should I put it?)

A question: does our version of MkDocs create a pdf/ebook document like the 'hosted' does? If not, is it easy to add? That would definitely be a big big plus.

**Comment by seanmadsen** [comment]
PDF/ebook creation is a separate feature, tracked in #11. I have not researched it yet. If you want to help with this, that would be great!

**Comment by seanmadsen** [comment]
@nganivet:
 > keep the drop-down to switch versions in the UI, in a very similar way it was done for the wiki 

Yes, I agree that this interface is best. But unfortunately my research thus far tells me that implementing something like this within our current docs system will be a *lot* of work, which is why I'm proposing using the docs home page as a way to switch versions. Perhaps I'm wrong though, do you have an idea for how to implement it that would be easy?

**Comment by nganivet** [comment]
This would be a fairly easy Javascript snippet to write (get the URL, extract version info, display drop-down with other version names/URLs and eventually warning). The only difficulty would be if we need to check that each target exists (ie. a page for a new hook in master will not exist in 4.6), but if we leave this aside for now (maybe with a small warning that the destination pages might not exist) then this is fairly easy.

**Comment by seanmadsen** [comment]
@nganivet Cool. I'm glad you think it will be fairly easy. Given your "Javascript snippet" approach, I think we can basically add this feature to the running list of features to implement in our custom theme. I would love to have your help on implementing it when the custom theme is up and running.

**Comment by nganivet** [comment]
Yep, count on me.

Sent from my iPhone

On Jan 30, 2017, at 11:22 AM, Sean Madsen <notifications@github.com> wrote:

@nganivet <https://github.com/nganivet> Cool. I'm glad you think it will be
fairly easy. Given your "Javascript snippet" approach, I think we can
basically add this feature to the running list of features to implement in
our custom theme. I would love to have your help on implementing it when
the custom theme is up and running.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/civicrm/civicrm-docs/issues/33#issuecomment-276145874>,
or mute the thread

**Comment by colemanw** [comment]
FYI I wrote the javascript snippet which displays the "you are viewing 
the current/archived version" bar on the wiki. It's not perfect because 
if wiki pages don't have exactly the same title & url from version to 
version it gets lost, but other than that it works.

**Comment by nganivet** [comment]
Coleman - if you send me this snippet I can adapt it for mkdocs. Thanks.

------ Original Message ------

**Comment by seanmadsen** [comment]
I'm closing this issue now, since we have [civicrm-docs-material#4](https://github.com/civicrm/civicrm-docs-material/issues/4) to track further work on it
