### ISSUE TITLE
How do we include theme customizations in this repo?

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-docs#36]
So, we have a separate repository, [civicrm-docs-material](https://github.com/civicrm/civicrm-docs-material) for the theme customizations which was part of my [plan](https://github.com/civicrm/civicrm-docs/issues/15#issuecomment-276156953), but now I'm doubting this choice a bit, after talking with @michaelmcandrew today. I'd like some advice on the best way to proceed here, especially from @totten 

The theme customizations need to be accessible (and current)

* (A): on www-prod when publishing books
* (B): locally for theme developers to use with `mkdocs serve`
* (C): locally for civicrm-docs developers after doing `civibuild docs`

So the question is, how do we store the theme customizations to best meet all these needs. Here are ideas that emerged from my convo with Michael

1. `civicrm-docs-material` as a git submodule within `civicrm-docs`
1.  theme customizations stored within `civicrm-docs` directly (and we get rid of the separate repo)
1. something else?

I don't have an opinion. Do others? (Sorry if it was a bit premature to create that new repo and add 6 issues within it! :grimacing: )

**Comment by totten** [comment]
I'd say there's four situations:
 * (A): www-prod when publishing books
 * (B): locally for theme developers to use with `mkdocs serve`
 * (C): locally for civicrm-docs developers after doing `civibuild create docs`
 * (D): locally for content authors using `mkdocs serve` (who want realistic previews)

Approach depends how important it is to support B+D working with the proper theme. I'd lean toward `#2` because it's simpler and (mostly) I don't think B+D matter too much:
 * If you're developing the theme, then do `civibuild create docs` like anyone else working on the docs infra.
 * If you're writing content, just live with the default theme.

However, if some retentive type really wants a path to support B+D, then I'd do "something else":
 * Keep `civicrm-docs-material.git` as its own repo.
 * In `civicrm-docs-material.git`, have a `README.md` explaining how to use it.
 * In each book's git repo, the `README.md` should say something like: "If you want to use civicrm.org look-and-feel, follow instructions from `civicrm-docs-material`"
 * In `civicrm-docs.git`, use [`composer.json`](https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository) to bind loosely to the `civicrm/civicrm-docs-material@dev-master`.

Whenever one deploys an update to `civicrm-docs.git`, they should run `composer install && git scan up vendor/` to get latest code.

**Comment by seanmadsen** [comment]
Great. I agree that `#2` sounds good. I'll make it happen. Thanks for weighing in, @totten

**Comment by seanmadsen** [comment]
Closing now since we figured this out.
