### ISSUE TITLE
"Improve documentation" section: Page not found in the "currently shifting" link.

### ISSUE THREAD

**Issue by klonos** [civicrm/civicrm-docs#5]
It points to `https://civicrm.org/blog/michael-mcandrew/moving-civicrms-user-and-administrator-guide-gitbook-or-readthedocs` - should point to this instead:
https://civicrm.org/blog/michael-mcandrew/moving-civicrms-user-and-administrator-guide-to-gitbook-or-readthedocs

(there's a missing "to" before the word "gitbook")

@michaelmcandrew @totten, This was more of an issue with the website rather than with documentation itself, but the issue queue for the https://github.com/civicrm/civicrm-website-org repo is not enabled. What is the best way to notify you guys of such issues?

**Comment by totten** [comment]
@klonos, for an issue that's tied to the `*.civicrm.org` web presence (rather than the main CiviCRM codebase), the issue usually goes to http://issues.civicrm.org/ under the "Infrastructure" (INFRA) project.

For clarification... the issue sounds like a stale link (`...guide-gitbook-or-readthedocs` vs `...guide-to-gitbook-or-readthedocs`). But where do you see this link? (What is "it" in "it points https://..."?)

**Comment by totten** [comment]
Oh, I see it in `https://civicrm.org/improve-documentation` . Fixing.

**Comment by totten** [comment]
Aside: for something with a trivial fix like this, you can also report on https://chat.civicrm.org/ (under the "Infrastructure" channel).

**Comment by klonos** [comment]
Thanx @totten ...it's that for BackdropCMS.org we use the GitHub issue queue and I thought CiviCRM would use tit too. Now I know for next time.
